### ISSUE TITLE
parseUrl fails when the url contains query

### ISSUE THREAD

**Issue by marcgeeklaberge** [IonicaBizau/parse-url#73]
Any url containing a query (?) is currently failing in version 8.1.0.

```
const link = 'https://www.google.ca/search?q=hello;
  try {
    const parsedUrl = parseUrl(link);
    console.log('parseUrl no problem', parsedUrl);
  } catch (error) {
    console.log('parseUrl problem', JSON.stringify(error));
  }
```
` LOG  parseUrl problem {"subject_url":"https://www.google.ca/search?q=hello"}` **in version 8.1.0**
` LOG  parseUrl no problem {"hash": "", "host": "www.google.ca", "href": "https://www.google.ca/search?q=hello", "parse_failed": false, "password": "", "pathname": "/search", "port": "", "protocol": "ssh", "protocols": ["ssh"], "query": {}, "resource": "www.google.ca", "search": "", "user": "git"}` **in version 8.0.0**

Any plan to fix that?

**Comment by Tholkappiar** [comment]
Hello Maintainers , Can I work on this issue ?

**Comment by IonicaBizau** [comment]
This was fixed I think:

```js
{
  protocols: [ 'https' ],
  protocol: 'https',
  port: '',
  resource: 'www.google.ca',
  host: 'www.google.ca',
  user: '',
  password: '',
  pathname: '/search',
  hash: '',
  search: 'q=hello',
  href: 'https://www.google.ca/search?q=hello',
  query: { q: 'hello' },
  parse_failed: false
}
```

**Comment by ChaossAdept7** [comment]
I can reproduce this issue on 9.2.0, this string that was mentioned above "https://www.google.ca/search?q=hello" still failing
